name: Deploy GH-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      REDIRECT_URL: https://wmc-ahif-2021.github.io/Kipper-Web/
      UPDATE_SCRIPT: https://gist.githubusercontent.com/Luna-Klatzer/a6f57a7ad7d79dc0a90115846cc98945/raw/834133b554fa5ef35316614783dea8d1e69a92d6/insert-html-banner.py
      SCRIPT_FILE_NAME: insert-html-banner.py
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Run Setup for "tree"
        run: sudo apt-get install tree
      - name: Installs dependencies
        run: |
          npm install -g parcel@2.0.1
          npm install -g @parcel/core@2.0.1
          npm install -g @parcel/transformer-webmanifest@2.0.1
          npm install -g @parcel/transformer-image@2.0.1
          npm install -g @parcel/packager-raw-url@2.0.1
          npm install -g typescript@4.4.3
          npm install -g ts-node@3.3.0
          npm install -g tslib@2.3.1
          npm install -g set-value@4.1.0
          npm install -g json-schema@0.4.0
          npm install -g uuid@8.3.2
          npm install -g source-map-resolve@0.6.0
      - name: Insert Disclaimer Header
        run: |
          curl -o ${{ env.UPDATE_SCRIPT }} ${{ env.SCRIPT_FILE_NAME }}
          python insert-html-banner.py
      - name: Build Files using Parcel
        run: parcel build src/index.html --public-url ${{ env.REDIRECT_URL }} --dist-dir .
      - name: Add Local Identification Config
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name  "github-actions"
      - name: Commit changes to main
        run: |
          git add .
          git commit -m "Updated parcel build"
          git push origin +main:gh-pages --force
