name: Deploy GH-Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: |
        mv ./dist/ /tmp/kipper-dist/
        rm -rf .*
        mv /tmp/kipper-dist/* .
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - uses: EndBug/add-and-commit@v7
      with:
        message: 'Updated parcel build'
        add: '.'
        branch: gh-pages
        push: '--force -u origin gh-pages --set-upstream'
        default_author: github_actions
